### ISSUE TITLE
Scale link shortening

### ISSUE THREAD

**Issue by wipeyadocsoff** [wipeyadocsoff/blm.to#4]
Currently using Netlify's `_redirects` to store links that are shortened. This makes it to where people need a github account to add links, which is not ideal.

Some proposed solution:

- Collect links to be shortened via a form and use Netlify's serverless functions to re-direct at the CDN edge until build is completed. Some open questions:
  - How can we make sure the service isn't being used for non-blm related info without the PR review process in place? Auditing the links could be an answer.
  - How do we make sure a re-direct isn't clobbering a markdown page being used as an info directory?

- Host a form that interacts with an SCM bot that opens a PR for reviewers to confirm a re-direct add. Can use webhooks for notifications.
  - Will probably require a good bit of help reviewing but necessary in either scenario.

**Comment by wipeyadocsoff** [comment]
1. I might hold off on some of the bail resources specifically because another open source repo is handling that (redirected their currently)

2. It’s deployed via Netlify rn because it’s pretty great for automatic builds and DNS related stuff 

3. Possibly, i’m open to suggestions here!

**Comment by dlegs** [comment]
I agree with @illegalprime on the form+pr bot. Can be thrown together quick with bootstrap and express, would maybe need some error checking for dupes and invalid chars.

I've never worked with Netlify but looking into it.

**Comment by illegalprime** [comment]
@wipeyadocsoff this was implemented by #11 , we should close this.
